#ifndef CONSTANTS_H
#define CONSTANTS_H

// Arm States
enum State { REST, UP, DOWN };

// Control Modes
enum ControlMode { JOYSTICK, FLEXSENSOR, IMU };

//  Motor constant speed (max PWM = 255)
const int CONSTANT_SPEED = 255;


// Joystick
#define JOYSTICK_REST_POSITION 495
#define JOYSTICK_UP_THRESHOLD_LOW 0
#define JOYSTICK_UP_THRESHOLD_HIGH 200
#define JOYSTICK_DOWN_THRESHOLD_LOW 800
#define JOYSTICK_DOWN_THRESHOLD_HIGH 1023

// IMU
#define IMU_ACCEL_THRESHOLD_CHANGE_HIGH 0.5
#define IMU_ACCEL_THRESHOLD_CHANGE_LOW -0.5
#define IMU_ACCEL_THRESHOLD_REST_HIGH 0.1
#define IMU_ACCEL_THRESHOLD_REST_LOW -0.1
#define IMU_PITCH_THRESHOLD_MOVE 10
#define IMU_PITCH_THRESHOLD_REST 5

#endif